sudo: required
language: go
go:
  - master

before_install:
  - sudo apt-get update -y
  - sudo apt-get install python-pygments -y

install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install

before_script:
  - rm -rf public || exit 0

script:
  - hugo

deploy:
  provider: pages
  target-branch: master
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: sources

